### ISSUE TITLE
Not running issue

### ISSUE THREAD

**Issue by Zeljko9999** [e-sim-python/scripts#24]
Hi again. Everything what I mention in this post is runned by Android. I will put here two exmples, first buy_CC and second fly. I am using the latest version of codes that you edited yesterday (script master). When I use buy_cc its not working that should work, it always buy only 2 offers, for example: if I put buy amount:500 it will buy only 2 first offers but it should buy more bcs offers on MM are eg. 20 CC . It should print more links, but always print 1 as you can see. And then script not running. Just stopping. Not finish executing.  
![20210406_143808](https://user-images.githubusercontent.com/81927348/113713209-56096480-96e7-11eb-94ce-428a79987705.jpg)

I tried to fix that and I think the problem is with get_content (from login.py file). Everything work till there. First loop tour is executing good, while second tour stop on line 28. 
![20210406_143738](https://user-images.githubusercontent.com/81927348/113713709-efd11180-96e7-11eb-8d2a-acb853e65f6e.jpg)

The same problem is with flight, it flighht only once and then stop. 
![20210406_144804](https://user-images.githubusercontent.com/81927348/113713835-1000d080-96e8-11eb-9570-2309fa32be23.jpg)

So I am not sure is problem on my side or in the code. Thank you!

**Comment by Random-guy-on-internet** [comment]
@Hacki123 Hi, I've tested them myself, but since I'm not playing exura server, my resources are limited(f.e I don't have q5 tickets, gold, etc), and couldn't do more testings.
so, there might be issues that I'm unaware of.

----
bought 60 CC with buy_cc script

![IMG_20210406_223648](https://user-images.githubusercontent.com/66680456/113759032-dd77c780-9729-11eb-882d-6b3d969586fb.jpg)

RESULTS:

![Screenshot_1](https://user-images.githubusercontent.com/66680456/113759310-2e87bb80-972a-11eb-96bd-f4f018edf5bf.jpg)

----
travel with q1 tickets:

![IMG_20210406_224112](https://user-images.githubusercontent.com/66680456/113759038-dfda2180-9729-11eb-8c22-1bfd6e48157c.jpg)

**Comment by Zeljko9999** [comment]
So its probably my side problem. Ok thank you.

**Comment by Random-guy-on-internet** [comment]
@Hacki123 your welcome, you can try delete `cookies.txt` and `login_details.csv` file in `Help_function` folder and try the scripts again, that might solve some issues.

**a more advanced solution** instead of deleting those files would be adding this line to the top of your method in the script, run the scripts once and delete the line or comment it out for later use with a `#` sign.

```py
await login(server, clear_cookies=True)

# this line is a comment and wont be executed. so to comment out that line, just add a `#` to start of the line like so.

# await login(server, clear_cookies=True)
```
for example in buy_cc file you can do it like so:
-----
```py
import asyncio
from random import randint

from login import get_content, login


async def cc(server, country_id, max_price, buy_amount):
    """
    Buying specific amount of coins, up to a pre-determined price.
    (It can help if there are many small offers, like NPC)"""
    URL = f"https://{server}.e-sim.org/"
    max_price, buy_amount = float(max_price), float(buy_amount)
    bought_amount = 0
    
    # THIS LINE IS ADDED, you can comment it out after ran it once.
    await login(server, clear_cookies=True)
    
    for Index in range(10):  # 10 pages
        tree = await get_content(f"{URL}monetaryMarket.html?buyerCurrencyId={country_id}", login_first=not Index)
        IDs = tree.xpath("//td[4]//form[1]//input[@value][2]")
        IDs = [ID.value for ID in IDs]
        amounts = tree.xpath('//td[2]//b/text()')
        prices = tree.xpath("//td[3]//b/text()")
        for ID, amount, price in zip(IDs, amounts, prices):
            try:
                amount, price = float(amount), float(price)
                if price <= max_price and bought_amount <= buy_amount:
                    payload = {'action': "buy", 'id': ID,
                               'ammount': amount if amount <= buy_amount - bought_amount else buy_amount - bought_amount}
                    url = await get_content(f"{URL}monetaryMarket.html?buyerCurrencyId={country_id}", data=payload)
                    print(url)
                    if "MM_POST_OK_BUY" not in str(url):
                        return
                    else:
                        bought_amount += amount
                    await asyncio.sleep(randint(0, 2))
                    # sleeping for a random time between 0 and 2 seconds. feel free to change it
                else:
                    return
            except Exception as error:
                print(error)
                await asyncio.sleep(5)

if __name__ == "__main__":
    print(cc.__doc__)
    server = input("Server: ")
    country_id = input("Country id: ")
    max_price = float(input("Max price (included): "))
    buy_amount = float(input("How much coins you want to buy? "))
    loop = asyncio.get_event_loop()
    loop.run_until_complete(
        cc(server, country_id, max_price, buy_amount))
    input("Press any key to continue")
```

good luck.

**Comment by Zeljko9999** [comment]
Deleting cookies.txt helping,  but only first time of running it works, when I run second time its again not working. And that added line is not helping, I need to delete cookies manually. It is obviously there is problem on my side. Thanks anyway.
