### ISSUE TITLE
hi

### ISSUE THREAD

**Issue by Aztu333** [e-sim-python/scripts#6]
I run the script on the phone, I have some questions.
It works fine when the phone is on but when I turn the screen off it stops, I turn on wake-up lock and get wifilock uda again but it gets stops.
https://prnt.sc/viguez

My second question is, can we make the script hit for 2 servers at the same time?

**Comment by Random-guy-on-internet** [comment]
Hello, to answer first question, there might be a setting in your android device that will terminate background applications in order to save battery, maybe do a search in google to find a solution for that.

And for second question, i wasnt able to run 2 scripts simultaneously within **Py Droid 3**.
but im certain its possible if you really want to do it, all you have to do is searching google and spending some spare time on it.
here is a starting point : [How to Run Multiple Copies of the Same Android App](https://www.google.com/search?&q=How+to+Run+Multiple+Copies+of+the+Same+Android+App)
